[project]
name = "gearbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flowkit>=1.2.3",
    "torchvision>=0.22.0",
]
